version: "3.7"

services:
  betting:
    container_name: betting
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./data:/data
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sleep infinity

