version: "3.7"

services:
  betting:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./app:/workspace/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
        - redis
    # Command to keep the container running
#    command: tail -f /dev/null

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

networks:
  default:
    driver: bridge