version: "3.7"

services:
  betting:
    build:
        context: .
        dockerfile: Dockerfile
        target: dev
    container_name: betting
    volumes:
      - ./app:/app
      - ./data:/data
      - ./models:/models
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: sleep infinity

