version: "3.7"

services:
  betting:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./app:/workspace/app
    env_file:
      - .env
    network_mode: "bridge"
    ports:
      - "8000:8000"
    # Command to keep the container running
#    command: tail -f /dev/null
