<BalancePlot>
    MDGridLayout:
        id: info_box
        size_hint_y: 0.25
        pos_hint: {'top': 1}
        cols: 2

        MDLabel:
            id: model_name
            font_style: 'H6'
            theme_text_color: 'Primary'
            text: 'Model Name: '

        MDLabel:
            id: model_acc
            font_style: 'H6'
            theme_text_color: 'Primary'
            text: 'Accuracy: 00.00%'

        MDLabel:
            id: gambler_name
            font_style: 'H6'
            theme_text_color: 'Primary'
            text: 'Gambler Name'

        MDLabel:
            id:gambler_avg_profit
            font_style: 'H6'
            theme_text_color: 'Primary'
            text: 'Avg Profit: $0'

    MDBoxLayout:
        id: plot_box
        size_hint_y: 0.75
