MDFloatLayout:
    MDProgressBar:
        id: red_conf_bar
        color: 1, 0, 0, 1
        size_hint: 0.35, 1
        pos_hint: {'x': 0.15, 'y': -0.2}
        reversed: True
        value: 0
        max: 1
        min: 0

    MDLabel:
        id: red_conf_label
        text: '--.--%'
        font_style: 'H6'
        halign: 'center'
        pos_hint: {'x': -0.4, 'y': -0.2}
        color: 1, 0, 0, 1

    MDProgressBar:
        id: blue_conf_bar
        color: 0, 0, 1, 1
        size_hint: 0.35, 1
        pos_hint: {'x': 0.5, 'y': -0.2}
        value: 0
        max: 1
        min: 0

    MDLabel:
        id: blue_conf_label
        text: '--.--%'
        font_style: 'H6'
        halign: 'center'
        pos_hint: {'x': 0.4, 'y': -0.2}
        color: 0, 0, 1, 1

    MDProgressBar:
        id: red_odds_bar
        color: 1, 0, 0, 1
        size_hint: 0.35, 1
        pos_hint: {'x': 0.15, 'y': -0.3}
        reversed: True
        value: 0
        max: 1
        min: 0

    MDLabel:
        id: red_odds_label
        text: '--.--%'
        font_style: 'H6'
        halign: 'center'
        pos_hint: {'x': -0.4, 'y': -0.3}
        color: 1, 0, 0, 1

    MDProgressBar:
        id: blue_odds_bar
        color: 0, 0, 1, 1
        size_hint: 0.35, 1
        pos_hint: {'x': 0.5, 'y': -0.3}
        value: 0
        max: 1
        min: 0

    MDLabel:
        id: blue_odds_label
        text: '--.--%'
        font_style: 'H6'
        halign: 'center'
        pos_hint: {'x': 0.4, 'y': -0.3}
        color: 0, 0, 1, 1

    MDLabel:
        id: red_pot
        text: '$-,---,---'
        font_style: 'H6'
        halign: 'center'
        pos_hint: {'x': -0.2, 'y': -0.4}
        color: 1, 0, 0, 1

    MDLabel:
        id: blue_pot
        text: '$-,---,---'
        font_style: 'H6'
        halign: 'center'
        pos_hint: {'x': 0.2, 'y': -0.4}
        color: 0, 0, 1, 1

    MDLabel:
        id: matchup_count_label
        text: 'Matchup Count: -'
        font_style: 'H6'
        halign: 'center'
        pos_hint: {'x': 0.0, 'y': -0.45}

    MDLabel:
        id: conf_label
        text: 'Model Confidence'
        font_style: 'H6'
        halign: 'center'
        pos_hint: {'x': 0, 'y': -0.18}
        color: 1, 1, 1, 1

    MDLabel:
        id: odds_label
        text: 'Popular Odds'
        font_style: 'H6'
        halign: 'center'
        pos_hint: {'x': 0, 'y': -0.28}
        color: 1, 1, 1, 1

    MDLabel:
        id: red_team
        text: '-'
        font_style: 'H6'
        halign: 'center'
        pos_hint: {'x': -0.2, 'y': -0.1}
        color: 1, 0, 0, 1

    MDLabel:
        id: blue_team
        text: '-'
        font_style: 'H6'
        halign: 'center'
        pos_hint: {'x': 0.2, 'y': -0.1}
        color: 0, 0, 1, 1

    MDLabel:
        id: balance_label
        text: ''
        font_style: 'H6'
        font_size: '35sp'
        halign: 'center'
        pos_hint: {'x': 0, 'y': 0.35}
        color: 0, 1, 0, 1

    MDLabel:
        id: winner_label
        text: ''
        font_style: 'H6'
        font_size: '30sp'
        halign: 'center'
        pos_hint: {'x': -0.2, 'y': 0.15}
        color: 1, 0, 0, 1

    MDLabel:
        id:payout_label
        text: ''
        font_style: 'H6'
        font_size: '30sp'
        halign: 'center'
        pos_hint: {'x': 0.2, 'y': 0.15}
        color: 0, 1, 0, 1

    MDLabel:
        id: startup_label
        text: 'Waiting for a new match to begin...'
        font_style: 'H6'
        font_size: '45sp'
        halign: 'center'
        pos_hint: {'x': 0, 'y': 0.1}
        color: 1, 1, 1, 1

    MDLabel:
        id: bet_amount_label
        text: 'Bet Amount: $0'
        font_style: 'H6'
        font_size: '30sp'
        halign: 'center'
        pos_hint: {'x': 0, 'y': 0.0}
        color: 1, 1, 1, 1
